#!/bin/sh

IMG="$1"

WIDTH=$(identify -format "%w" "$IMG")
HEIGHT=$(identify -format "%h" "$IMG")

W=16
H=$(($W*$HEIGHT/$WIDTH))

mkdir -p tiles

rm -f tiles/*
magick "$IMG" -crop ${W}x${H}@ tiles/tile-%04d.png

for TILE in tiles/*; do
    mogrify +repage -gravity Center -crop 50%\! "$TILE"
done

montage -mode concatenate -tile ${W}x${H} tiles/* "$IMG-pixelated.png"
